/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as ApiTestRouteImport } from './routes/api-test'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRagRouteImport } from './routes/_layout/rag'
import { Route as LayoutFilesRouteImport } from './routes/_layout/files'
import { Route as LayoutErrorsRouteImport } from './routes/_layout/errors'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutConvertRouteImport } from './routes/_layout/convert'
import { Route as LayoutFilesIndexRouteImport } from './routes/_layout/files.index'
import { Route as LayoutFilesFileIdRouteImport } from './routes/_layout/files.$fileId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api-test',
  path: '/api-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRagRoute = LayoutRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesRoute = LayoutFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutErrorsRoute = LayoutErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConvertRoute = LayoutConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesIndexRoute = LayoutFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutFilesRoute,
} as any)
const LayoutFilesFileIdRoute = LayoutFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => LayoutFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/api-test': typeof ApiTestRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/convert': typeof LayoutConvertRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/errors': typeof LayoutErrorsRoute
  '/files': typeof LayoutFilesRouteWithChildren
  '/rag': typeof LayoutRagRoute
  '/settings': typeof LayoutSettingsRoute
  '/files/$fileId': typeof LayoutFilesFileIdRoute
  '/files/': typeof LayoutFilesIndexRoute
}
export interface FileRoutesByTo {
  '/api-test': typeof ApiTestRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/convert': typeof LayoutConvertRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/errors': typeof LayoutErrorsRoute
  '/rag': typeof LayoutRagRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/files/$fileId': typeof LayoutFilesFileIdRoute
  '/files': typeof LayoutFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/api-test': typeof ApiTestRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/_layout/convert': typeof LayoutConvertRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/errors': typeof LayoutErrorsRoute
  '/_layout/files': typeof LayoutFilesRouteWithChildren
  '/_layout/rag': typeof LayoutRagRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/files/$fileId': typeof LayoutFilesFileIdRoute
  '/_layout/files/': typeof LayoutFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-test'
    | '/bootstrap'
    | '/login'
    | '/convert'
    | '/dashboard'
    | '/errors'
    | '/files'
    | '/rag'
    | '/settings'
    | '/files/$fileId'
    | '/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api-test'
    | '/bootstrap'
    | '/login'
    | '/convert'
    | '/dashboard'
    | '/errors'
    | '/rag'
    | '/settings'
    | '/'
    | '/files/$fileId'
    | '/files'
  id:
    | '__root__'
    | '/_layout'
    | '/api-test'
    | '/bootstrap'
    | '/login'
    | '/_layout/convert'
    | '/_layout/dashboard'
    | '/_layout/errors'
    | '/_layout/files'
    | '/_layout/rag'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/files/$fileId'
    | '/_layout/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiTestRoute: typeof ApiTestRoute
  BootstrapRoute: typeof BootstrapRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-test': {
      id: '/api-test'
      path: '/api-test'
      fullPath: '/api-test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rag': {
      id: '/_layout/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof LayoutRagRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files': {
      id: '/_layout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/errors': {
      id: '/_layout/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof LayoutErrorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/convert': {
      id: '/_layout/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof LayoutConvertRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/': {
      id: '/_layout/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof LayoutFilesIndexRouteImport
      parentRoute: typeof LayoutFilesRoute
    }
    '/_layout/files/$fileId': {
      id: '/_layout/files/$fileId'
      path: '/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof LayoutFilesFileIdRouteImport
      parentRoute: typeof LayoutFilesRoute
    }
  }
}

interface LayoutFilesRouteChildren {
  LayoutFilesFileIdRoute: typeof LayoutFilesFileIdRoute
  LayoutFilesIndexRoute: typeof LayoutFilesIndexRoute
}

const LayoutFilesRouteChildren: LayoutFilesRouteChildren = {
  LayoutFilesFileIdRoute: LayoutFilesFileIdRoute,
  LayoutFilesIndexRoute: LayoutFilesIndexRoute,
}

const LayoutFilesRouteWithChildren = LayoutFilesRoute._addFileChildren(
  LayoutFilesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutConvertRoute: typeof LayoutConvertRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutErrorsRoute: typeof LayoutErrorsRoute
  LayoutFilesRoute: typeof LayoutFilesRouteWithChildren
  LayoutRagRoute: typeof LayoutRagRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutConvertRoute: LayoutConvertRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutErrorsRoute: LayoutErrorsRoute,
  LayoutFilesRoute: LayoutFilesRouteWithChildren,
  LayoutRagRoute: LayoutRagRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiTestRoute: ApiTestRoute,
  BootstrapRoute: BootstrapRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
